### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null - followed by flakey code insight.

### ISSUE THREAD

**Issue by web-engineer** [php-integrator/atom-tooltips#22]
Steps unclear - wasn't doing much at the time - just completed getting 2.1 installed then closed a tab and opened a php script and immediately got this error.

Quit/Restart and didn't happen again - opened a project and after indexing tested the code insight and it just starts indexing (without progress ) and stopped working.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [php-integrator-tooltips](https://github.com/php-integrator/atom-tooltips) package, v1.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/craig/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:107

TypeError: Cannot read property 'add' of null
    at ClassProvider.module.exports.AbstractProvider.registerEvents (/Users/craig/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:107:21)
    at ClassProvider.module.exports.AbstractProvider.registerEventsForPane (/Users/craig/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:85:22)
    at /Users/craig/.atom/packages/php-integrator-tooltips/lib/AbstractProvider.coffee:63:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.didDestroyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:316:27)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:869:53)
    at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:851:39)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:590:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:643:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:711:17)
```

### Commands

```
     -9:28 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:24.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:13.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:10.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -9:07.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -9:02.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.14 (inactive)
build-tools-ant, v0.1.1 (active)
file-icons, v1.7.25 (active)
hyperclick, v0.0.39 (active)
php-class-tree, v1.0.0 (inactive)
php-integrator-annotations, v1.1.0 (active)
php-integrator-autocomplete-plus, v1.2.0 (active)
php-integrator-base, v2.1.0 (active)
php-integrator-call-tips, v1.2.0 (active)
php-integrator-linter, v1.3.0 (active)
php-integrator-navigation, v1.1.0 (active)
php-integrator-symbol-viewer, v0.6.4 (active)
php-integrator-tooltips, v1.1.0 (active)
project-manager, v3.3.3 (active)
to-base64, v0.5.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
I've added a sanity check that should fix it.
